### ISSUE TITLE
cant use with gke

### ISSUE THREAD

**Issue by cypctlinux** [niusmallnan/kube-explorer#1]
we use gke service, when run service it response bellow

FATA[0000] no Auth Provider found for name "gcp"

**Comment by niusmallnan** [comment]
@cypctlinux The gke cluster has something different.
You can try install kube-explorer by Pod.

GKE requires a user to manually claim themselves as cluster-admin to enable role-based access control. Before installing kube-explorer, run the following command:
```
kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=<name@example.com>
```

Then, install the kube-explorer deployment.
```
git clone https://github.com/cnrancher/kube-explorer
cd kube-explorer/deploy/kubectl
kubectl create -f .
# edit svc type to NodePort if needed
kubectl edit svc kube-explorer -n kube-system
```
