### ISSUE TITLE
打开首页，页面提示出错

### ISSUE THREAD

**Issue by HofmannHe** [niusmallnan/kube-explorer#10]
版本：`v0.2.3`
系统：`Centos 7.9`
命令行：`./kube-explorer --kubeconfig=./k3s.yaml--http-listen-port=9898 --https-listen-port=0`

现象：
- Chrome浏览器（版本号71.0）打开首页，蛇形Logo下提示Error:Promise[t] is not a function(抱歉因为纯内网环境无法截图)

**Comment by niusmallnan** [comment]
我的chrome版本是 94.0.4606.81，并没有发现前端报错。

**Comment by HofmannHe** [comment]
> 我的chrome版本是 94.0.4606.81，并没有发现前端报错。

是的，就是Chrome版本问题，换了94.xx就好了
