### ISSUE TITLE
Node list page shows wrong role

### ISSUE THREAD

**Issue by kingsd041** [niusmallnan/kube-explorer#13]
kube-explorer version: v0.2.8
k3s version: v1.22.7+k3s1

<img width="590" alt="image" src="https://user-images.githubusercontent.com/19684717/160987801-8a3e9fd6-eacd-45a5-a580-6e2fd6a3e8b5.png">

<img width="779" alt="image" src="https://user-images.githubusercontent.com/19684717/160987832-81a279bb-0162-44e1-b11c-39847a296132.png">

**Comment by niusmallnan** [comment]
@kingsd041 let's transfer this issue to `rancher/dashboard`. I can ask someone to fix it upstream.
