### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by fsdrw08** [niusmallnan/kube-explorer#14]
any luck to add windows binary?

**Comment by niusmallnan** [comment]
Sorry, I used to compile the Windows version, but many users found problems when testing. The log is normal, but the browser cannot access it.

I have no experience in Windows adaptation, so I removed the windows binary.

**Comment by masoudei** [comment]
Hey guys, hello, are you from the original rancher team ? or not?
Is this project's source available? if it is based on HTML, js, ... I think we can make a way like Lens and OpenLens to use Electron for cross-platform builds . Can I contribute?

**Comment by niusmallnan** [comment]
Yes, I am from Rancher, and based in China.
Those js and html files are embedded into the Golang binary.
Golang supports cross-platform for Windows binary, but after running, I cannot access the web service. I'm not a Windows expert, and don't have a Windows usage scenario, so didn't take the time to troubleshoot it.

Any references in this project are public and free to use.

**Comment by orangedeng** [comment]
You can try v0.3.4-rc3 version. I fixed the windows runtime problem.

**Comment by feisc** [comment]
两位大佬，我在阿里云的服务器上用make dev 编译时，用zypper下载安装包的速度很慢，并且还出错，
![image](https://github.com/cnrancher/kube-explorer/assets/22266880/89333bfc-dbb4-4223-ad23-7b9408ff867e)
请问如何解决下载速度慢，以及编译错误的问题@orangedeng @niusmallnan

**Comment by orangedeng** [comment]
Try to use HongKong region machine to compile this project. Github access is not reliable in Mainland China. `zypper install` should be fine.

Sometimes it will have difficulties to install golangci-lint, you can replace it with `go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2` which is source code installation way.

And please to open a separated issue for your question.

**Comment by orangedeng** [comment]
Already supported windows binary in v0.4.0. Closing this issue
