### ISSUE TITLE
registry secrets 不显示

### ISSUE THREAD

**Issue by lyc8503** [niusmallnan/kube-explorer#16]
在 secrets 中添加了 registry secrets
![image](https://user-images.githubusercontent.com/36782264/178510181-7913ba9b-6351-47a0-a9ce-294a625591d7.png)
但在 deployment 中没有显示
![image](https://user-images.githubusercontent.com/36782264/178510272-c6374755-dd0e-4d81-98b4-0182caf1861f.png)

**Comment by niusmallnan** [comment]
@ly5156 I confirmed this is a bug, it exists in the kube-explorer. I did not reproduce this issue in the Rancher Cluster Explorer.

**Comment by ly5156** [comment]
@niusmallnan 
After I synchronized the code with version v2.6.7-rc5(kube-explorer-ui:`v2.6.7-rc5-kube-explorer-ui-rc1`), I verified that the problem no longer recurred

**Comment by niusmallnan** [comment]
Fixed in v0.2.10-rc3.
