### ISSUE TITLE
关闭 kubectl shell 后相关对象未被清理

### ISSUE THREAD

**Issue by mikeyzm** [niusmallnan/kube-explorer#20]
版本：autok3s v0.5.2-rc2 随附的 kube-explorer v0.2.9

每次打开 kubectl shell 都会创建 `ClusterRoleBinding` `ClusterRole` `ConfigMap` 等对象，但关闭后并未对这些对象进行清理。

## 复现步骤

1. 进入 kube-explorer
2. 点击右上角 kubectl shell
3. 关闭 shell 窗口
4. 重复以上操作，观察到上述类型的孤立对象不断增加

![image](https://user-images.githubusercontent.com/3685044/183438069-57a46842-f32f-45e9-bac3-5bc834ea6b9d.png)

## 预期行为

关闭 shell 后清理相关对象

**Comment by niusmallnan** [comment]
Thanks for your detailed issue. 
Right! These orphan resources should be cleaned up.

**Comment by niusmallnan** [comment]
It should be fixed by [v0.2.10-rc4](https://github.com/cnrancher/kube-explorer/releases/tag/v0.2.10-rc4).
