### ISSUE TITLE
mac m1 support?

### ISSUE THREAD

**Issue by xcbeyond** [niusmallnan/kube-explorer#21]

**Comment by niusmallnan** [comment]
I haven't bought a Mac M1 yet, in theory just use the proper `go build` parameters. I will look for equipment to test.

**Comment by niusmallnan** [comment]
Fixed by [v0.2.10-rc5](https://github.com/cnrancher/kube-explorer/releases/download/v0.2.10-rc5/kube-explorer-darwin-arm64) .

**Comment by xcbeyond** [comment]
> Fixed by [v0.2.10-rc5](https://github.com/cnrancher/kube-explorer/releases/download/v0.2.10-rc5/kube-explorer-darwin-arm64) .

[v0.2.10-rc5](https://github.com/cnrancher/kube-explorer/releases/download/v0.2.10-rc5/kube-explorer-darwin-arm64) won't work on mac m1。
