### ISSUE TITLE
pull secrets option display mismatch when creating workload 

### ISSUE THREAD

**Issue by zzl221000** [niusmallnan/kube-explorer#22]
Expect: Show only `Kind: Registry `
Actual: All Secrets

**Comment by niusmallnan** [comment]
I have opened a ticket to the upstream. https://github.com/rancher/dashboard/issues/6725

**Comment by ly5156** [comment]
The [pr](https://github.com/rancher/dashboard/pull/6733) to fix this issue has been merged, the next version will include this fix

**Comment by niusmallnan** [comment]
Fixed by v0.2.12-rc1.
