### ISSUE TITLE
Unexpected result in cronjobs page sorted by Last Schedule or Age

### ISSUE THREAD

**Issue by zzl221000** [niusmallnan/kube-explorer#24]
Last schedule and age will be resolved to human readable units, but should be sorted by actual values.

### Expectation
Sorted by datetime string

### Actual 
Sort by human readable string

**Comment by niusmallnan** [comment]
Not sure if I understand what you mean.
However, if you wish to adjust the sorting rules, you can click on the table header to adjust the ascending and descending order.

**Comment by zzl221000** [comment]
> Not sure if I understand what you mean. However, if you wish to adjust the sorting rules, you can click on the table header to adjust the ascending and descending order.

Strange sorting results. 
I've been descending by Last Schedule.
![image](https://user-images.githubusercontent.com/14102425/187332857-9b605072-b4e6-4f4a-a130-3147802cac3a.png)

**Comment by ly5156** [comment]
@zzl221000
Which the version of the`kube-explorer` are you using?

**Comment by niusmallnan** [comment]
@zzl221000 It should be fixed by v0.2.12-rc1. Could you please try this out?

**Comment by zzl221000** [comment]
@niusmallnan  v0.2.12-rc1 worked well .
