### ISSUE TITLE
Failed to start since last commit

### ISSUE THREAD

**Issue by icexxxxxx** [niusmallnan/kube-explorer#28]
Create Aliyun cluster using Autok3s:

ERRO[2022-10-25T11:49:33+08:00] fail to start kube-explorer for cluster k3s-cluster.cn-shanghai.alibaba: fork/exec /usr/local/bin/kube-explorer: exec format error

I started to use autok3s and kube-explorer since last Friday, it worked in the begining when I created cluster in the quick way for testing.
Then I switched to the detailed way to create cluster, and it failed till now. The cluster is good to go, except the explorer.

Looking for your help! 😥 @niusmallnan

**Comment by niusmallnan** [comment]
**kube-explorer: exec format error**

Can you try running kube-explorer manually? This hint is already obvious.

**Comment by icexxxxxx** [comment]
> **kube-explorer: exec format error**
> 
> Can you try running kube-explorer manually? This hint is already obvious.

Thx. 
The kube-explorer installed by autok3s installation script was not doing well. I replaced it with the latest release and manually started successfully.
