### ISSUE TITLE
CRD support?

### ISSUE THREAD

**Issue by liyimeng** [niusmallnan/kube-explorer#29]
Thanks for the great work. This tiny tool is cool. However, I am wondering if can support crd resource. I download and run it to explore my cluster. All k8s standard resource can be seen from the UI, but none CRD showing up. Is this the way it supposed to be?

**Comment by niusmallnan** [comment]
@liyimeng The kube-explorer can show the CRD.
You can click the Resource Search icon in the upper right corner and try to retrieve the desired CRD. If you want to visit some specific CRDs frequently, you can click the five-pointed star to collect them.

**Comment by liyimeng** [comment]
@niusmallnan superb! I found it, so cool!  I see Steve support auth webhook, and cube-explorer use basic auth via ingress. Can we add a simple auth webhook?

**Comment by niusmallnan** [comment]
I thought the user would run kube-explorer locally and only allow localhost access.

I'm concerned that simple basic auth is being abused causing a lot of security issues.

**Comment by niusmallnan** [comment]
Allowing access to webhook auth is a good idea. However, I'm not too familiar with whether there is a good standard for webhook auth.

**Comment by liyimeng** [comment]
Thanks for the info! @niusmallnan I saw some webhook auth code in Steve code base, hence think there might some work in progress.
