### ISSUE TITLE
Click  run now in cronjob will not show the generated pod

### ISSUE THREAD

**Issue by zzl221000** [niusmallnan/kube-explorer#32]
~~The controller-uid label selector is missing from the manually generated pod~~

**Comment by zzl221000** [comment]
Actually, the ownerReferences field is missing

**Comment by niusmallnan** [comment]
I just created an issue upstream.
Let's track this: https://github.com/rancher/dashboard/issues/8683

**Comment by niusmallnan** [comment]
Fixed in v0.3.3
