### ISSUE TITLE
如何设置账号密码

### ISSUE THREAD

**Issue by 983183947** [niusmallnan/kube-explorer#33]
服务启动后都是直接就进入系统了感觉不安全，我要如何设置账号密码登录

**Comment by niusmallnan** [comment]
你可以自己搭建反向代理，在代理中加入适合自身的鉴权配置。
这里是一种参考：https://github.com/cnrancher/kube-explorer/blob/main/deploy/kubectl/nginx-auth/ingress.yaml.tpl

**Comment by whk06** [comment]
请问可以直接把Rancher登录页面拿来使用吗？是否可以集成到kube-explorer的二进制文件内呢？
@niusmallnan
