### ISSUE TITLE
will support mangement multi k8s cluster?

### ISSUE THREAD

**Issue by xinmans** [niusmallnan/kube-explorer#35]

**Comment by orangedeng** [comment]
Try Rancher if you want to manage multi- cluster.

**Comment by xinmans** [comment]
> Try Rancher if you want to manage multi- cluster.

I see kube-explorer have rancher face, why?

**Comment by orangedeng** [comment]
Because the kube-explorer is the light weight version of the Rancher explorer UI for single cluster.
Rancher has the multi-k8s lifecycle management and all kinds of tools you need for your clusters.

**Comment by orangedeng** [comment]
Closing this issue. Feel free to re-open if you have further questions.
