### ISSUE TITLE
multi-kubeconfig

### ISSUE THREAD

**Issue by bingzhuan** [niusmallnan/kube-explorer#4]
How to support multi-kubeconfig  ?  I'd like to check my rancher information  in one web portal .  

thx.

-----------------------------------------------------------------------------
kube-explorer --kubeconfig=xxxx --http-listen-port=9898--https-listen-port=0

**Comment by niusmallnan** [comment]
That is not this project's target.
We will integrate kube-explorer to autok3s(https://github.com/cnrancher/autok3s) to support the multi-cluster management, it is more like a rancher-lite version.
