### ISSUE TITLE
kube-explorer  启动放到后台之后 崩溃了

### ISSUE THREAD

**Issue by guoyahao** [niusmallnan/kube-explorer#5]
环境：
vmware  centos7 加 k3s 

启动命令：
/home/kube-explorer --kubeconfig=/root/.kube/config --http-listen-port=9898 --https-listen-port=0 >>/home/kube-explorer.log  2>&1 &

下面是记录到的日志：

W0514 15:58:21.697574   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0514 15:58:21.706767   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
time="2021-05-14T15:58:21+08:00" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=RoleBinding controller"
time="2021-05-14T15:58:21+08:00" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=Role controller"
time="2021-05-14T15:58:21+08:00" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller"
time="2021-05-14T15:58:21+08:00" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding controller"
time="2021-05-14T15:58:21+08:00" level=info msg="Starting apiregistration.k8s.io/v1, Kind=APIService controller"
time="2021-05-14T15:58:21+08:00" level=info msg="Starting apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition controller"
time="2021-05-14T15:58:21+08:00" level=info msg="Listening on :9898"
time="2021-05-14T15:58:22+08:00" level=info msg="Refreshing all schemas"
time="2021-05-14T15:58:22+08:00" level=info msg="Refreshing all schemas"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind Binding"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind ComponentStatus"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind ConfigMap"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind Endpoints"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind Event"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind LimitRange"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind Namespace"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind Node"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind PersistentVolumeClaim"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind PersistentVolume"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind Pod"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind PodTemplate"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind ReplicationController"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind ResourceQuota"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind Secret"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind ServiceAccount"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion /v1 Kind Service"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion apiregistration.k8s.io/v1 Kind APIService"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion apiregistration.k8s.io/v1beta1 Kind APIService"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion apps/v1 Kind ControllerRevision"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion apps/v1 Kind DaemonSet"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion apps/v1 Kind Deployment"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion apps/v1 Kind ReplicaSet"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion apps/v1 Kind StatefulSet"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion events.k8s.io/v1 Kind Event"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion events.k8s.io/v1beta1 Kind Event"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion authentication.k8s.io/v1 Kind TokenReview"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion authentication.k8s.io/v1beta1 Kind TokenReview"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion authorization.k8s.io/v1 Kind LocalSubjectAccessReview"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion authorization.k8s.io/v1 Kind SelfSubjectAccessReview"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion authorization.k8s.io/v1 Kind SelfSubjectRulesReview"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion authorization.k8s.io/v1 Kind SubjectAccessReview"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion authorization.k8s.io/v1beta1 Kind LocalSubjectAccessReview"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion authorization.k8s.io/v1beta1 Kind SelfSubjectAccessReview"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion authorization.k8s.io/v1beta1 Kind SelfSubjectRulesReview"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion authorization.k8s.io/v1beta1 Kind SubjectAccessReview"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion autoscaling/v1 Kind HorizontalPodAutoscaler"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion autoscaling/v2beta1 Kind HorizontalPodAutoscaler"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion autoscaling/v2beta2 Kind HorizontalPodAutoscaler"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion batch/v1 Kind Job"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion batch/v1beta1 Kind CronJob"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion certificates.k8s.io/v1 Kind CertificateSigningRequest"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion certificates.k8s.io/v1beta1 Kind CertificateSigningRequest"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion networking.k8s.io/v1 Kind IngressClass"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion networking.k8s.io/v1 Kind Ingress"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion networking.k8s.io/v1 Kind NetworkPolicy"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion networking.k8s.io/v1beta1 Kind IngressClass"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion networking.k8s.io/v1beta1 Kind Ingress"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion extensions/v1beta1 Kind Ingress"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion policy/v1beta1 Kind PodDisruptionBudget"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion policy/v1beta1 Kind PodSecurityPolicy"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion rbac.authorization.k8s.io/v1 Kind ClusterRoleBinding"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion rbac.authorization.k8s.io/v1 Kind ClusterRole"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion rbac.authorization.k8s.io/v1 Kind RoleBinding"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion rbac.authorization.k8s.io/v1 Kind Role"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion rbac.authorization.k8s.io/v1beta1 Kind ClusterRoleBinding"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion rbac.authorization.k8s.io/v1beta1 Kind ClusterRole"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion rbac.authorization.k8s.io/v1beta1 Kind RoleBinding"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion rbac.authorization.k8s.io/v1beta1 Kind Role"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion storage.k8s.io/v1 Kind CSIDriver"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion storage.k8s.io/v1 Kind CSINode"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion storage.k8s.io/v1 Kind StorageClass"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion storage.k8s.io/v1 Kind VolumeAttachment"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion storage.k8s.io/v1beta1 Kind CSIDriver"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion storage.k8s.io/v1beta1 Kind CSINode"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion storage.k8s.io/v1beta1 Kind StorageClass"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion storage.k8s.io/v1beta1 Kind VolumeAttachment"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion admissionregistration.k8s.io/v1 Kind MutatingWebhookConfiguration"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion admissionregistration.k8s.io/v1 Kind ValidatingWebhookConfiguration"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion admissionregistration.k8s.io/v1beta1 Kind MutatingWebhookConfiguration"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion admissionregistration.k8s.io/v1beta1 Kind ValidatingWebhookConfiguration"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion apiextensions.k8s.io/v1 Kind CustomResourceDefinition"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion apiextensions.k8s.io/v1beta1 Kind CustomResourceDefinition"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion scheduling.k8s.io/v1 Kind PriorityClass"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion scheduling.k8s.io/v1beta1 Kind PriorityClass"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion coordination.k8s.io/v1 Kind Lease"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion coordination.k8s.io/v1beta1 Kind Lease"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion node.k8s.io/v1 Kind RuntimeClass"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion node.k8s.io/v1beta1 Kind RuntimeClass"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion discovery.k8s.io/v1beta1 Kind EndpointSlice"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion flowcontrol.apiserver.k8s.io/v1beta1 Kind FlowSchema"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion flowcontrol.apiserver.k8s.io/v1beta1 Kind PriorityLevelConfiguration"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion helm.cattle.io/v1 Kind HelmChart"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion helm.cattle.io/v1 Kind HelmChartConfig"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion k3s.cattle.io/v1 Kind Addon"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion devices.edge.cattle.io/v1alpha1 Kind ModbusDevice"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion devices.edge.cattle.io/v1alpha1 Kind BluetoothDevice"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion devices.edge.cattle.io/v1alpha1 Kind MQTTDevice"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion devices.edge.cattle.io/v1alpha1 Kind OPCUADevice"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion edge.cattle.io/v1alpha1 Kind DeviceLink"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion octopusapi.cattle.io/v1alpha1 Kind Setting"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion octopusapi.cattle.io/v1alpha1 Kind DeviceTemplate"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion octopusapi.cattle.io/v1alpha1 Kind DeviceTemplateRevision"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion octopusapi.cattle.io/v1alpha1 Kind Catalog"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion metrics.k8s.io/v1beta1 Kind NodeMetrics"
time="2021-05-14T15:58:22+08:00" level=info msg="APIVersion metrics.k8s.io/v1beta1 Kind PodMetrics"
W0514 15:58:22.455325   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=Service"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for devices.edge.cattle.io/v1alpha1, Kind=MQTTDevice"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for networking.k8s.io/v1, Kind=IngressClass"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for k3s.cattle.io/v1, Kind=Addon"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for flowcontrol.apiserver.k8s.io/v1beta1, Kind=PriorityLevelConfiguration"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=Secret"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for batch/v1beta1, Kind=CronJob"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for edge.cattle.io/v1alpha1, Kind=DeviceLink"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for events.k8s.io/v1, Kind=Event"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for flowcontrol.apiserver.k8s.io/v1beta1, Kind=FlowSchema"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=PersistentVolumeClaim"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=ServiceAccount"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=PersistentVolume"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for apps/v1, Kind=DaemonSet"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for devices.edge.cattle.io/v1alpha1, Kind=BluetoothDevice"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for helm.cattle.io/v1, Kind=HelmChartConfig"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for storage.k8s.io/v1, Kind=CSIDriver"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for discovery.k8s.io/v1beta1, Kind=EndpointSlice"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for networking.k8s.io/v1, Kind=Ingress"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for devices.edge.cattle.io/v1alpha1, Kind=OPCUADevice"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for apiregistration.k8s.io/v1, Kind=APIService"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for autoscaling/v2beta2, Kind=HorizontalPodAutoscaler"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=Node"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for rbac.authorization.k8s.io/v1, Kind=ClusterRole"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for apps/v1, Kind=Deployment"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for policy/v1beta1, Kind=PodDisruptionBudget"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for storage.k8s.io/v1, Kind=CSINode"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=Event"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=PodTemplate"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for storage.k8s.io/v1, Kind=StorageClass"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for octopusapi.cattle.io/v1alpha1, Kind=DeviceTemplate"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for apps/v1, Kind=StatefulSet"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=ResourceQuota"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for rbac.authorization.k8s.io/v1, Kind=Role"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for storage.k8s.io/v1, Kind=VolumeAttachment"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=Pod"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for node.k8s.io/v1, Kind=RuntimeClass"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for coordination.k8s.io/v1, Kind=Lease"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for devices.edge.cattle.io/v1alpha1, Kind=ModbusDevice"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for certificates.k8s.io/v1, Kind=CertificateSigningRequest"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for apps/v1, Kind=ReplicaSet"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for policy/v1beta1, Kind=PodSecurityPolicy"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for networking.k8s.io/v1, Kind=NetworkPolicy"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=ConfigMap"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=Namespace"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for helm.cattle.io/v1, Kind=HelmChart"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=ReplicationController"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for scheduling.k8s.io/v1, Kind=PriorityClass"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for octopusapi.cattle.io/v1alpha1, Kind=Setting"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for batch/v1, Kind=Job"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for rbac.authorization.k8s.io/v1, Kind=RoleBinding"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for octopusapi.cattle.io/v1alpha1, Kind=DeviceTemplateRevision"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for octopusapi.cattle.io/v1alpha1, Kind=Catalog"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=LimitRange"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for /v1, Kind=Endpoints"
time="2021-05-14T15:58:22+08:00" level=info msg="Watching metadata for apps/v1, Kind=ControllerRevision"
time="2021-05-14T16:04:17+08:00" level=error msg="Error during subscribe websocket: close sent"
time="2021-05-14T16:04:17+08:00" level=error msg="Error during subscribe websocket: close sent"
time="2021-05-14T16:04:23+08:00" level=error msg="Error during subscribe websocket: close sent"
time="2021-05-14T16:04:23+08:00" level=error msg="Error during subscribe websocket: close sent"
W0514 16:06:47.707930   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
time="2021-05-14T16:10:42+08:00" level=error msg="Error during subscribe write tcp 192.168.101.129:9898->192.168.101.1:52432: write: broken pipe"
W0514 16:16:21.710084   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
time="2021-05-14T16:20:13+08:00" level=error msg="Error during subscribe write tcp 192.168.101.129:9898->192.168.101.1:52460: write: broken pipe"
W0514 16:23:00.712928   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0514 16:32:50.716396   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0514 16:40:07.717496   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0514 16:43:15.078192   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 16:43:15.080531   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 16:43:15.109231   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 16:43:15.109346   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 16:50:02.718479   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0514 16:56:10.721367   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0514 16:57:30.477566   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 16:57:30.478075   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 16:57:30.519553   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 16:57:30.538458   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 17:01:57.722639   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0514 17:10:56.727165   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0514 17:13:20.899996   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 17:13:20.902668   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 17:13:20.930667   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 17:13:20.949182   70665 transport.go:260] Unable to cancel request for *client.addQuery
time="2021-05-14T17:13:34+08:00" level=error msg="Error during subscribe websocket: close sent"
time="2021-05-14T17:13:34+08:00" level=error msg="Error during subscribe websocket: close sent"
W0514 17:16:04.729339   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0514 17:21:07.731454   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
time="2021-05-14T17:24:51+08:00" level=error msg="Error during subscribe websocket: close sent"
time="2021-05-14T17:24:51+08:00" level=error msg="Error during subscribe websocket: close sent"
W0514 17:28:26.736444   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0514 17:35:29.737206   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0514 17:43:26.862136   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 17:43:26.864633   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 17:43:26.888163   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 17:43:26.912545   70665 transport.go:260] Unable to cancel request for *client.addQuery
W0514 17:43:42.739727   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0514 17:51:12.742223   70665 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
time="2021-05-14T17:54:46+08:00" level=error msg="Error during subscribe write tcp 192.168.101.129:9898->192.168.101.1:52724: write: broken pipe"

**Comment by niusmallnan** [comment]
怎么判断是”崩溃“？我没有看到fatal level logs，warning和error level是允许的。

**Comment by guoyahao** [comment]
因为是放到后台执行，放了1天 没有继续请求了 ，然后今天再去请求 就发现进程没了

**Comment by niusmallnan** [comment]
没有新的线索，暂时关闭
